# Работа с одномерным массивом

In [ ]:
import numpy as np

In [11]:
lst = [1, 2, 3, 4]

arr = np.array(lst)

print(arr)  # полученный массив
print(arr.dtype)  # тип данных массива
print(arr.ndim)  # количество изменений в массиве
print(arr.shape)  # размер массива в 1-ом измерении

# размер массива
print(arr.size)
print(len(arr))

[1 2 3 4]
(4,)
int64
1
4
4


In [9]:
arr2 = np.arange(0, 20, 1.5)
# в отличие от range в Python, arange умеет работать с дробными числами
print(arr2)

arr2 = np.linspace(0, 2, 5)
# передает 5 чисел от 0 до 2
print(arr2)

[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.  16.5 18.  19.5]
[0.  0.5 1.  1.5 2. ]


In [22]:
# 5 случайных чисел
arr3 = np.random.random((5,))
print(arr3)
arr3 = np.random.random_sample((5,))
print(arr3)

# диапазон случайных чисел от [a,b]: (b-a)*np.random()+a, где b>a
# пример на 5 числах в интревале от -5 до 10
arr3 = (10 - -5) * np.random.random_sample((5,)) - 5
print(arr3)
arr3 = np.random.randint(-5, 10, 5)
print(arr3)

[0.34929551 0.70570812 0.36080102 0.88754484 0.51818826]
[0.83011102 0.30682314 0.27996419 0.26350065 0.04493541]
[ 7.20417375 -3.21332787 -2.3041517  -3.1154639   7.30727212]
[ 1 -5 -4 -4  4]


In [20]:
# операции

# примеры некоторых мат. функций из многих
arr4 = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr4))  # квадратный корень
print(np.sin(arr4))  # синус
print(np.cos(arr4))  # косинус
print(np.log(arr4))  # логарифм
print(np.exp(arr4))  # экспонента

# примеры мат. операций
arr5 = np.array([1, 2, 3, 4, 5])
arr6 = np.array([6, 7, 8, 9, 10])
print(np.add(arr5,arr6))  # arr5 + arr6 – сложение
print(np.subtract(arr5,arr6))  # arr5 - arr6 – вычитание
print(np.multiply(arr5,arr6))  # arr5 * arr6 – произведение
print(np.divide(arr5,arr6))  # arr5 / arr6 – деление
print(arr5 * 2)  # умножит все элементы массива на 2 (со списком так нельзя)
print(arr5 ** 2)  # возвести все элементы во 2 степень (со списком так нельзя)

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
