# Работа с одномерным массивом

In [ ]:
import numpy as np

In [36]:
lst = [1, 2, 3, 4]

arr = np.array(lst)

print(arr)  # полученный массив
print(arr.dtype)  # тип данных массива
print(arr.ndim)  # количество изменений в массиве
print(arr.shape)  # размер массива в 1-ом измерении

arr = np.array(arr, dtype=np.float64)  # преобразование типа данных массива
print(arr)

# размер массива
print(arr.size)
print(len(arr))

[1 2 3 4]
int64
1
(4,)
[1. 2. 3. 4.]
4
4


In [25]:
arr2 = np.arange(0, 20, 1.5)
# в отличие от range в Python, arange умеет работать с дробными числами
print(arr2)

arr2 = np.linspace(0, 2, 5)
# передает 5 чисел от 0 до 2
print(arr2)

[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.  16.5 18.  19.5]
[0.  0.5 1.  1.5 2. ]


In [26]:
# рандомные числа 

# 5 случайных чисел
arr3 = np.random.random((5,))
print(arr3)
arr3 = np.random.random_sample((5,))
print(arr3)

# диапазон случайных чисел от [a,b]: (b-a)*np.random()+a, где b>a
# пример на 5 числах в интревале от -5 до 10
arr3 = (10 - -5) * np.random.random_sample((5,)) - 5
print(arr3)
arr3 = np.random.randint(-5, 10, 5)
print(arr3)

[0.64257051 0.90431023 0.95123847 0.9652271  0.96957514]
[0.07414941 0.88147406 0.30628298 0.3904202  0.81895439]
[ 1.53594918  0.72790771  0.92974968 -0.46946233  6.41696043]
[ 8 -5  9  4  1]


In [20]:
# операции

arr4 = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr4))  # квадратный корень
print(np.sin(arr4))  # синус
print(np.cos(arr4))  # косинус
print(np.log(arr4))  # логарифм
print(np.exp(arr4))  # экспонента

arr5 = np.array([1, 2, 3, 4, 5])
arr6 = np.array([6, 7, 8, 9, 10])
print(np.add(arr5,arr6))  # arr5 + arr6 – сложение
print(np.subtract(arr5,arr6))  # arr5 - arr6 – вычитание
print(np.multiply(arr5,arr6))  # arr5 * arr6 – произведение
print(np.divide(arr5,arr6))  # arr5 / arr6 – деление
print(arr5 * 2)  # умножит все элементы массива на 2 (со списком так нельзя)
print(arr5 ** 2)  # возвести все элементы во 2 степень (со списком так нельзя)

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [24]:
# функции агрегаты
arr7 = np.array([1, 2, 3, 4, 5])
print(arr7.max())
print(arr7.min())
print(arr7.mean())
print(arr7.sum())
print(arr7.std())
print(np.median(arr7))
print(arr7 < 2)

5
1
3.0
15
1.4142135623730951
3.0
[ True False False False False]


In [34]:
# манипуляции с массивами 
arr8 = np.array([5, 4, 3, 2, 1])
print(arr8)
arr8 = np.insert(arr8, 2, 999)
print(arr8)
arr8 = np.delete(arr8, 2)
print(arr8)
arr8 = np.sort(arr8)
print(arr8)
arr8 = np.concatenate((np.array([0,1]), np.array([2,3])))
print(arr8)
arr8 = np.array_split(arr8, 3)
print(arr8)

[5 4 3 2 1]
[  5   4 999   3   2   1]
[5 4 3 2 1]
[1 2 3 4 5]
[0 1 2 3]
[array([0, 1]), array([2]), array([3])]


In [39]:
# индексы
arr9 = np.array([1, 2, 3, 4, 5])
arr9[0] = 0
print(arr9)
print(arr9[2])
print(arr9[0:2])
print(arr9[::-1])
print(arr9[arr9 < 2])
print(arr9[(arr9 < 2) & (arr9 > 0)])
print(arr9[(arr9 > 4) | (arr9 < 0)])
arr9[1:4] = 0
print(arr9)

[0 2 3 4 5]
3
[0 2]
[5 4 3 2 0]
[0]
[]
[5]
[0 0 0 0 5]


### Далее работа с матрицами