# Матрицы (двумерные массивы)

In [2]:
import numpy as np

In [8]:
# основное

matrix = np.array([(1,2,3), (4,5,6)])
print(matrix)
print(matrix.dtype)  # тип данных массива
print(matrix.ndim)  # количество изменений в массиве
print(matrix.shape)  # размер массива в 2-ом измерении
print(matrix.size)  # размер массива


[[1 2 3]
 [4 5 6]]
int64
2
(2, 3)
6
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3. 4. 5. 6.]]
[[1. 2.]
 [3. 4.]]


In [21]:
# преобразование матрицы

matrix2 = np.array([(1,2,3), (4,5,6), (7,8,9)])

matrix2 = np.array(matrix2, dtype=np.float64)  # преобразование типа данных массива
print(matrix2)

matrix2 = matrix.reshape(1,9)  # преобразование матрицы на массив в 1 ряд с 6 элементами (изменение формы массива)
print(matrix2)

matrix2 = np.resize(matrix, (2,2))  # преобразование матрицы() на 
print(matrix2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 2 3 4 5 6 7 8 9]]
[[1 2]
 [3 4]]


In [7]:
# рандомные числа

matrix3 = np.random.random((2,2))
print(matrix3)

[[0.21510655 0.34662696]
 [0.06869905 0.91622121]]


In [13]:
# комбинирование методов

matrix4 = np.arange(16).reshape(2,8)
print(matrix4)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [25]:
# специальные матрицы

matrix5 = np.zeros((2,3))  # матрица 2х3, заполненная 0
print(matrix5)

matrix5 = np.ones((3,3))  # матрица 3х3, заполненная 1
print(matrix5)

matrix5 = np.eye(5)  # единичная матрица 5 порядка
print(matrix5)

matrix5 = np.full((3,3), 9)  # матрица 3х3, заполненная 9
print(matrix5)

matrix5 = np.empty((3,2))  # пустая матрица 3х2
print(matrix5)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [33]:
# операции

matrix6 = np.array([(1,2), (3,4)])
matrix7 = np.array([(5,6), (7,8)])

print(np.add(matrix6,matrix7))  # matrix6 + matrix7 – сложение
print(np.subtract(matrix6,matrix7))  # matrix6 - matrix7 – вычитание
print(np.multiply(matrix6,matrix7))  # matrix6 * matrix7 – произведение
print(np.divide(matrix6,matrix7))  # matrix6 / matrix7 – деление
print(matrix6.dot(matrix7))  # скалярное произведение

# axis: ось 0 - ось рядов в матрице, ось 1 - ось столбцов в матрице

matrix8 = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(matrix8)

matrix8 = np.delete(matrix8,1,axis=0)  # удаление 1 ряда 
print(matrix8)

matrix8 = np.delete(matrix8,1,axis=1)  # удаление 1 столбца 
print(matrix8)

print(np.log(matrix8))  # логарифм
print(np.sin(matrix8))  # синус
print(matrix8.sum())  # сумма
print(matrix8.max())  # максимальный элемент
print(matrix8.max(axis=0))  # максимальный ряд
print(np.mean(matrix8, axis=0))  # рассчет среднего значения по рядам
print(np.mean(matrix8, axis=1))  # рассчет среднего значения по столбцам

print(matrix8 ** 2)  # возвездение во 2 степень


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [7 9]]
[[0.         1.09861229]
 [1.94591015 2.19722458]]
[[0.84147098 0.14112001]
 [0.6569866  0.41211849]]
20
9
[7 9]
[4. 6.]
[2. 8.]
[[ 1  9]
 [49 81]]


In [36]:
# склеивание матриц и разделение матрицы

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

arr2 = np.array([[7,8,9],[10,11,12]])
print(arr2)

# склеивание матриц столбцами
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

arr = np.hstack((arr1,arr2))
print(arr)

# склеивание матриц рядами
arr = np.concatenate((arr1,arr2), axis=0)
print(arr)

arr = np.vstack((arr1,arr2))
print(arr)

# разделение матрицы на 2
arr = np.split(arr1,2)
print(arr)

# разделение матрицы на 2 по рядам
arr = np.split(arr1,2,axis=0)
print(arr)

# разделение матрицы на 3 на столбцам
arr = np.split(arr1,3,axis=1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [37]:
# индексация 

matrix9 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(matrix9)
print(matrix9[1,2])
print(matrix9[2])
print(matrix9[:,2])
print(matrix9[matrix9 > 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[7 8 9]
[3 6 9]
[3 4 5 6 7 8 9]


In [39]:
# специальные операции 

print(matrix9)
print(matrix9.T)  # транспонирование
print(matrix9.flatten())  # в массив
print(np.linalg.inv(matrix9))  # обратная матрица
print(np.trace(matrix9))  # след матрицы
print(np.linalg.det(matrix9))  # определитель матрицы
print(np.linalg.matrix_rank(matrix9))  # ранк

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
15
-9.51619735392994e-16
2
